### PR TITLE
Make [U]int64.toString precise for all values

### LINKED ISSUE #66: Uint64.toString fails for large numbers
For example:

```javascript
new jDataView.Uint64(12345678, 12345678).toString()  // "53024283269292370"
```

Whereas in Python, with arbitrary-precision numbers, I get:

```python
print 12345678 * 2**32 + 12345678  # 53024283269292366
```

These differ in the last decimal.

The `.valueOf()` method has to round off, but there's no reason `.toString()` should.

### PR DESCRIPTION
**Pull request by danvk**
Fixes #66 

That was fun! This adds ~60 LOC to `jdataview.js`, but it does result in more correct behavior. See [this post][1] for background.

[1]: http://www.danvk.org/hex2dec.html

### CODE REVIEW

File: dist/jdataview.js [hunk 1]
```diff
@@ -1,23 +1,23 @@
...
-		}
-		else {
-			global.jDataView = factory(global);
-		}
-	}
-}(function (global) {
-
-'use strict';
-
+(function (factory) {
```
Comment (RReverser) [inline dist/jdataview.js]: Any idea why those are highlighted as diffs? Looks like inconsistent whitespace either was there before or occurs now.

File: src/jdataview.js [hunk 2]
```diff
@@ -201,10 +201,6 @@ jDataView.Uint64 = Uint64;
 Uint64.prototype = {
 	valueOf: function () {
```
Comment (RReverser) [inline src/jdataview.js]: Please move `valueOf` outside as you did with `toString` for consistency (and because I was stupid when writing this :) ).

File: src/jdataview.js [hunk 3]
```diff
@@ -244,6 +240,71 @@ Int64.fromNumber = function (number) {
...
+		var digits = num.toString().split('');
+		for (var i = 0; i < digits.length; i++) {
+			digits[i] = +digits[i];
+		}
+		digits.reverse();
+		return digits;
+	};
+
+	// Adds two digit arrays for the given base, returning the result.
+	var add = function(x, y, base) {
```
Comment (RReverser) [inline src/jdataview.js]: I don't think we would need generic `base` in this case. Can you please inline it?

File: dist/jdataview.js (hunk 1 above)
Comment (danvk) [inline dist/jdataview.js]: Not at all -- I don't see these changes when I run `git diff origin/master dist/jdataview.js` in my client.

File: src/jdataview.js (hunk 2 above)
Comment (danvk) [inline src/jdataview.js]: Done

File: src/jdataview.js (hunk 3 above)
Comment (danvk) [inline src/jdataview.js]: Done

**Comment by danvk** [comment]
I addressed you comments. Feel free to have another look.

File: dist/jdataview.js (hunk 1 above)
Comment (RReverser) [inline dist/jdataview.js]: That's weird, Github wouldn't show difference if it wouldn't be there. Maybe different newlines and local `git` ignores them? If you don't find the reason, I can try on my own a bit later.

Comment (danvk) [inline dist/jdataview.js]: Ah, nm, you're right. It's different newlines. I'm on a Mac, perhaps that's
why?

File: src/jdataview.js [hunk 4]
```diff
@@ -244,6 +238,71 @@ Int64.fromNumber = function (number) {
...
+	// Faster toString() for numbers which can be represented precisely as floats.
+	if (this.hi < pow2(19)) {
+		return Number.prototype.toString.apply(this.valueOf(), arguments);
+	}
+
+	// This converts the numbers to base 10 digit arrays for arbitrary precision toString().
+	// See http://www.danvk.org/hex2dec.html
+
+	// e.g. 1234 -> [4, 3, 2, 1]
+	var numToDigits = function(num) {
```
Comment (RReverser) [inline src/jdataview.js]: This and `add` functions don't seem to depend on any scope variables and most engines are still stupid enough to recreate closures on each visit which is unwanted in our case. Could you please move them out (right before `toString`) as regular functions?

Comment (danvk) [inline src/jdataview.js]: Done

File: dist/jdataview.js (hunk 1 above)
Comment (RReverser) [inline dist/jdataview.js]: Yeah, could be the reason. I'd like to merge, but this isn't very pleasant if it will jump with each commit. Maybe would be better if you could PR source only, and I'll build & publish from my machine. Thanks for your patience!

Comment (danvk) [inline dist/jdataview.js]: Sure. I reverted the files in `dist` and pushed a squashed commit of all the changes to my fork.

FWIW, it's a bit unusual to include generated files in the git repo.

Comment (RReverser) [inline dist/jdataview.js]: Fair enough - initially it was just used in some demos via rawgit, and I didn't want to break them. And now, it doesn't matter much given that project is basically "finished" and changes don't occur often enough.

**Comment by RReverser** [comment]
Thanks! :fireworks:

**Comment by RReverser** [comment]
Oh great, some devDeps broke in Node 4.0 :(
